# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
