# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161101_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('professor', '教授'), ('a_professor', '副教授'), ('doctor', '博士'), ('master', '硕士')], max_length=10, null=True),
        ),
    ]
