# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('教授', '教授'), ('副教授', '副教授'), ('博士', '博士'), ('硕士', '硕士')], max_length=10, null=True),
        ),
    ]
