# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161119_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('教授', '教授'), ('副教授', '副教授'), ('博士', '博士'), ('硕士', '硕士')], max_length=10, null=True),
        ),
    ]
