# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161102_2042'),
        ('app', '0006_auto_20161120_1245'),
    ]

    operations = [
    ]
